# Generated by Django 5.0.4 on 2024-04-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_roomgame_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='topic',
            new_name='game',
        ),
    ]
