# Generated by Django 5.0.4 on 2024-04-28 22:25

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='../static/images/avatar.svg', null=True, upload_to=base.models.user_directory_path),
        ),
    ]
