# Generated by Django 5.0.4 on 2024-04-16 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_participants'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomGame',
            new_name='Game',
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
